# Configuração de Produção do Broker Mosquitto
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Listener 1: Rede Interna (Containers Backend)
listener 1883 0.0.0.0
allow_anonymous true

# Listener 2: MQTTS com TLS para os 250 Tablets
listener 8883 0.0.0.0
# cafile /mosquitto/certificados/ca.crt
# certfile /mosquitto/certificados/server.crt
# keyfile /mosquitto/certificados/server.key
# require_certificate false
